---
# e2e_action can be one of: all | setup | test
#e2e_action: all
e2e_tests_dir: /tmp/openshift_ws
e2e_tests_git: "https://github.com/openshift/origin"
e2e_tests_git_branch: "release-4.15"
e2e_max_parallel_test: 15
e2e_tests_exclude_list_url: ""
e2e_upgrade_image: ""
e2e_retest: false
golang_tarball: "https://dl.google.com/go/go1.22.0.linux-ppc64le.tar.gz"
github_token: ""

############################
e2e_env:
   PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
   KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"
   KUBE_TEST_REPO_LIST: /tmp/kube-test-repo-list
